apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: GitRepository
        name: grafana
        namespace: flux-system
      interval: 5m

  