apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/BrettOJ/jupyter-hub-helm-chart
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/jupyterhub/
